/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import controller.ClientController;
import domen.Cenovnik;
import domen.Dobavljac;
import domen.Proizvod;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Mina
 */
public class CenovnikKreirajForma extends javax.swing.JDialog {

    /**
     * Creates new form CenovnikKreirajForma
     */
    public CenovnikKreirajForma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        setLocationRelativeTo(null);
        pripremi();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbDobavljac = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtCena = new javax.swing.JFormattedTextField();
        btnSacuvaj = new javax.swing.JButton();
        cmbProizvod = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Proizvod:");

        jLabel2.setText("Dobavljač:");

        jLabel3.setText("Cena:");

        txtCena.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        btnSacuvaj.setText("SAČUVAJ");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtCena))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSacuvaj))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbDobavljac, 0, 300, Short.MAX_VALUE)
                            .addComponent(cmbProizvod, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbProizvod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbDobavljac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSacuvaj)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        // TODO add your handling code here:
        try {

            Proizvod proizvod = (Proizvod) cmbProizvod.getSelectedItem();
            if (proizvod == null) {
                throw new Exception("Morate izabrati neki proizvod!");
            }

            Dobavljac dobavljac = (Dobavljac) cmbDobavljac.getSelectedItem();
            if (dobavljac == null) {
                throw new Exception("Morate izabrati nekog dobavljača!");
            }

            double cena = Double.parseDouble(txtCena.getText());
            if (txtCena.getText().isEmpty()) {
                throw new Exception("Niste uneli cenu");
            }

            if(cena<=0){
                throw new Exception("Cena mora biti veća od 0");
            }
            
            Cenovnik cenovnik = new Cenovnik(dobavljac, proizvod, cena);
            
            ClientController.getInstanca().kreirajCenovnik(cenovnik);
            JOptionPane.showMessageDialog(rootPane, "Uspešno ste kreirali cenovnik");
            this.dispose();
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox<Object> cmbDobavljac;
    private javax.swing.JComboBox<Object> cmbProizvod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JFormattedTextField txtCena;
    // End of variables declaration//GEN-END:variables

    private void pripremi() {
        try{
            popuniKombo();
        }catch(Exception ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }
    
    private void izbaciIzCmb(Proizvod proizvod) {
        cmbProizvod.removeItem(proizvod);
    }

   
    /*private void ubaciProizvodUCmb(StavkaRacuna s) {
        Proizvod p = s.getProizvod();
        //p.setCena((BigDecimal) Sesija.getInstanca().vratiParametar("Cena"));
        cmbProizvod.addItem(p);
    }*/

    private void popuniKombo() {
        try {
            List<Proizvod> proizvodi = ClientController.getInstanca().prikaziProizvode();
            for (Proizvod proizvod : proizvodi) {
                cmbProizvod.addItem(proizvod);
                
            }
            
            List<Dobavljac> dobavljaci = ClientController.getInstanca().prikaziDobavljace();
            for (Dobavljac dobavljac : dobavljaci) {
                cmbDobavljac.addItem(dobavljac);
                
            }

            cmbProizvod.setSelectedIndex(-1);
            cmbDobavljac.setSelectedIndex(-1);
        } catch (Exception ex) {
          ex.printStackTrace();
          JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }
}
