/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import controller.ClientController;
import domen.Dobavljac;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Mina
 */
public class DobavljacKreirajForma extends javax.swing.JDialog {

    private Dobavljac dobavljac;

    /**
     * Creates new form DobavljacKreirajForma
     */
    public DobavljacKreirajForma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        setLocationRelativeTo(null);

    }

    public DobavljacKreirajForma(java.awt.Frame parent, boolean modal, Dobavljac dobavljac) {
        super(parent, modal);
        initComponents();
        this.dobavljac = dobavljac;
        setLocationRelativeTo(null);
        prepareView();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPIB = new javax.swing.JTextField();
        txtNazivDobavljaca = new javax.swing.JTextField();
        txtAdresaDobavljaca = new javax.swing.JTextField();
        txtEmailDobavljaca = new javax.swing.JTextField();
        txtBrojDobavljaca = new javax.swing.JTextField();
        btnSacuvaj = new javax.swing.JButton();
        btnIzadji = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("PIB:");

        jLabel2.setText("Naziv dobavljača:");

        jLabel3.setText("Adresa dobavljača:");

        jLabel4.setText("Email dobavljača:");

        jLabel5.setText("Broj dobavljača:");

        btnSacuvaj.setText("SAČUVAJ");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        btnIzadji.setText("IZAĐI");
        btnIzadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzadjiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPIB)
                    .addComponent(txtNazivDobavljaca)
                    .addComponent(txtAdresaDobavljaca)
                    .addComponent(txtEmailDobavljaca)
                    .addComponent(txtBrojDobavljaca, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(btnSacuvaj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(btnIzadji)
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPIB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNazivDobavljaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAdresaDobavljaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEmailDobavljaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtBrojDobavljaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSacuvaj)
                    .addComponent(btnIzadji))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        try {
            int pib = Integer.parseInt(txtPIB.getText());
            String nazivDob = txtNazivDobavljaca.getText();
            String adresaDob = txtAdresaDobavljaca.getText();
            String brojDob = txtBrojDobavljaca.getText();
            String emailDob = txtEmailDobavljaca.getText();

            if (txtPIB.getText().isEmpty()) {
                throw new Exception("Niste uneli PIB");
            }

            if (nazivDob.isEmpty()) {
                throw new Exception("Niste uneli naziv dobavljača");
            }

            if (adresaDob.isEmpty()) {
                throw new Exception("Niste uneli adresu dobavljača");
            }

            if (brojDob.isEmpty()) {
                throw new Exception("Niste uneli broj dobavljača");
            }

            if (emailDob.isEmpty()) {
                throw new Exception("Niste uneli email dobavljača");
            }
           

            if (this.dobavljac == null) {
                Dobavljac dobavljac= new Dobavljac(pib, nazivDob, adresaDob, emailDob, brojDob, new ArrayList<>());
                ClientController.getInstanca().kreirajDobavljaca(dobavljac);
                JOptionPane.showMessageDialog(rootPane, "Sistem je kreirao novog dobavljača");
            } else {
                
                
                dobavljac.setNazivDobavljaca(nazivDob);
                dobavljac.setAdresaDobavljaca(adresaDob);
                dobavljac.setBrojDobavljac(brojDob);
                dobavljac.setEmailDobavljaca(emailDob);
                
                ClientController.getInstanca().zapamtiDobavljaca(dobavljac);
                
                JOptionPane.showMessageDialog(rootPane, "Uspesno ste izmenili dobavljača");
            }

            this.dispose();
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Sistem ne može da sacuva dobavljača");
        }

    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void btnIzadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzadjiActionPerformed
        dispose();
    }//GEN-LAST:event_btnIzadjiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzadji;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtAdresaDobavljaca;
    private javax.swing.JTextField txtBrojDobavljaca;
    private javax.swing.JTextField txtEmailDobavljaca;
    private javax.swing.JTextField txtNazivDobavljaca;
    private javax.swing.JTextField txtPIB;
    // End of variables declaration//GEN-END:variables

    private void prepareView() {
        if (dobavljac != null) {
            try {
                
                txtPIB.setText("" + dobavljac.getPIB());
                txtPIB.setEnabled(false);
                txtNazivDobavljaca.setText(dobavljac.getNazivDobavljaca());
                txtAdresaDobavljaca.setText(dobavljac.getAdresaDobavljaca());
                txtEmailDobavljaca.setText(dobavljac.getEmailDobavljaca());
                txtBrojDobavljaca.setText(dobavljac.getBrojDobavljac());
            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Sistem ne može da učita dobavljača", "Greška", JOptionPane.ERROR_MESSAGE);
                dispose();
            }
        }

    }
}
