/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import controller.ClientController;
import domen.Dobavljac;
import domen.Proizvod;
import static java.awt.image.ImageObserver.ERROR;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import modeli.ModelTabeleDobavljaci;
import modeli.ModelTabeleProizvodi;
import sesijaa.Sesija;

/**
 *
 * @author Mina
 */
public class DobavljacPretragaForma extends javax.swing.JDialog {

    /**
     * Creates new form DobavljacPretragaForma
     */
    public DobavljacPretragaForma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        setLocationRelativeTo(null);
        try {
            txtStringTekst.setText("");
            Sesija.getInstanca().setPretragad(this);
            pripremiFormu(new ArrayList<>());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", ERROR);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtStringTekst = new javax.swing.JTextField();
        btnPretrazi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDobavljac = new javax.swing.JTable();
        btnIzmeni = new javax.swing.JButton();
        btnPonisti = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnPretrazi.setText("PRETRAŽI");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        tblDobavljac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDobavljac);

        btnIzmeni.setText("IZMENI");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnPonisti.setText("PONIŠTI");
        btnPonisti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPonistiActionPerformed(evt);
            }
        });

        jLabel1.setText("Pretraži po nazivu dobavljača:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPonisti)
                        .addGap(18, 18, 18)
                        .addComponent(btnIzmeni))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(txtStringTekst, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(123, 123, 123)
                            .addComponent(btnPretrazi))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStringTekst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretrazi)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIzmeni)
                    .addComponent(btnPonisti))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        // TODO add your handling code here:
        try {
            int red = tblDobavljac.getSelectedRow();
            if (red == -1) {
                JOptionPane.showMessageDialog(rootPane, "Sistem ne može da prikaže podatke o dobavljaču");
                return;
            }
            Dobavljac dob = ((ModelTabeleDobavljaci)tblDobavljac.getModel()).vratiDobavljaca(red);
            JOptionPane.showMessageDialog(rootPane, "Sistem je učitao dobavljača");
            new DobavljacKreirajForma(null, true, dob).setVisible(true);

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
        try {
            String kriterijum = txtStringTekst.getText();
            if (kriterijum.isEmpty()) {
                throw new Exception("Niste uneli kriterijum pretrage");
            }

            validacija(kriterijum);

            List<Dobavljac> listaDobavljaca = pretrazi(kriterijum);

            pripremiFormu(listaDobavljaca);
            JOptionPane.showMessageDialog(this, "Sistem je pronašao tražene dobavljače");
            btnPonisti.setEnabled(true);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Sistem ne može da nađe dobavljacče po zadatoj vrednosti");
        }


    }//GEN-LAST:event_btnPretraziActionPerformed

    private void btnPonistiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPonistiActionPerformed
        try {
            pripremiFormu(new ArrayList<>());
            txtStringTekst.setText("");
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_btnPonistiActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnPonisti;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDobavljac;
    private javax.swing.JTextField txtStringTekst;
    // End of variables declaration//GEN-END:variables

    

    private void validacija(String kriterijum) throws Exception {
        if (kriterijum.equals("")) {
            throw new Exception("Unesite uslov za pretragu!");
        }
    }

    private List<Dobavljac> pretrazi(String kriterijum) throws Exception {
        List<Dobavljac> dobavljaci = ClientController.getInstanca().pretraziDobavljace(kriterijum);
        if (dobavljaci.isEmpty()) {
            throw new Exception("Ne postoje dobavljači koji zadovoljavaju zadati kriterijum!");
        }
        return dobavljaci;
    }
    
    public void osvezi(Dobavljac dobavljac) {
        ModelTabeleDobavljaci model = (ModelTabeleDobavljaci) tblDobavljac.getModel();
        model.obrisiDobavljaca((Dobavljac) Sesija.getInstanca().vratiParametar("Dobavljac"));
        Sesija.getInstanca().obrisiParametar("Dobavljac");
        if (dobavljac != null) {
            Sesija.getInstanca().dodajParametar("Dobavljac", dobavljac);
            model.dodajDobavljaca(dobavljac);
        }
    }

    private void pripremiFormu(List<Dobavljac> listaDobavljaca) {
        try {
            if (listaDobavljaca.isEmpty()) {
                listaDobavljaca = ClientController.getInstanca().prikaziDobavljace();
                btnPonisti.setEnabled(false);
            }
            ModelTabeleDobavljaci model = new ModelTabeleDobavljaci(listaDobavljaca);
            tblDobavljac.setModel(model);
            Sesija.getInstanca().dodajParametar("Lista dobavljaca", model.getDobavljaci());
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}
