/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import controller.ClientController;
import domen.Dobavljac;
import domen.Proizvod;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Mina
 */
public class ProizvodKreirajForma extends javax.swing.JDialog {

    private Proizvod proizvod;

    /**
     * Creates new form ProizvodKreirajForma
     */
    public ProizvodKreirajForma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        setLocationRelativeTo(null);
    }

    public ProizvodKreirajForma(java.awt.Frame parent, boolean modal, Proizvod proizvod) {
        super(parent, modal);
        initComponents();
        this.proizvod = proizvod;
        setLocationRelativeTo(null);
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNazivProizvoda = new javax.swing.JTextField();
        txtOpis = new javax.swing.JTextField();
        btnSacuvaj = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Naziv proizvoda:");

        jLabel2.setText("Opis:");

        btnSacuvaj.setText("SAČUVAJ");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSacuvaj)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNazivProizvoda)
                            .addComponent(txtOpis, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNazivProizvoda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtOpis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btnSacuvaj)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        try {
            String nazivProizvoda = txtNazivProizvoda.getText();
            String opis = txtOpis.getText();

            if (nazivProizvoda.isEmpty()) {
                throw new Exception("Niste uneli naziv proizvoda");
            }
            if (opis.isEmpty()) {
                throw new Exception("Niste uneli opis proizvoda");
            }

            if (this.proizvod == null) {
                Proizvod proizvod = new Proizvod(0, nazivProizvoda, opis);

                ClientController.getInstanca().kreirajProizvod(proizvod);
                JOptionPane.showMessageDialog(rootPane, "Uspešno ste kreirali proizvod");
            } else {
                this.proizvod.setOpis(opis);
                ClientController.getInstanca().zapamtiProizvod(this.proizvod);
                JOptionPane.showMessageDialog(rootPane, "Uspešno ste izmenili proizvod");
            }

            //Proizvod proizvod = new Proizvod(0, nazivProizvoda, opis);
            // ClientController.getInstanca().kreirajProizvod(proizvod);
            // JOptionPane.showMessageDialog(rootPane, "Uspesno ste sacuvali proizvod");
            this.dispose();
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Sistem ne može da sačuva proizvod");
        }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtNazivProizvoda;
    private javax.swing.JTextField txtOpis;
    // End of variables declaration//GEN-END:variables

    private void prepareView() {
        if (proizvod != null) {
            try {
                txtNazivProizvoda.setText(proizvod.getNazivProizvoda());
                txtNazivProizvoda.setEnabled(false);
                txtOpis.setText(proizvod.getOpis() + "");
            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Sistem ne može da učita proizvod", "Greška", JOptionPane.ERROR_MESSAGE);
                dispose();
            }
        }
    }
}
